name = "ut-qms"
main = "index.ts"
compatibility_date = "2024-03-21"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# Add environment variables here

[[d1_databases]]
binding = "DB"
database_name = "ut-qms-db"
database_id = "9844bf0a-8208-449e-ae32-514064d65542"
